### ISSUE TITLE
Short Term Archive

### ISSUE THREAD

**Issue by sterlingbaldwin** [ACME-Climate/acme_processflow#17]
ACME runs using STA need to be supported. Additionally the directory structure created by STA needs to be replicated on the destination machine.

**Comment by golaz** [comment]
@rljacob is working on fixing the short term archiving (https://github.com/ACME-Climate/ACME/issues/1794), so this needs to be working with the processflow. We need options to look for input files either in the run subdirectory, or in the short term archive. The structure of the archive is as follows:

```
rest/yyyy-mm-dd-sssss/
logs/
atm/hist/
cpl/hist
glc/hist
ice/hist
lnd/hist
ocn/hist
rof/hist
wav/hist
```
Here is my best guess for locations of the files that we currently need:

```
cam.h0 : atm/hist/
streams : run/
mpaso.hist.* : ocn/hist/
mpascice.hist.* : ice/hist/
mpaso.rst.* : rest/yyyy-mm-dd-sssss/
mpas-cice_in : run/
```

**Comment by rljacob** [comment]
Related, I've started a discussion page on filename conventions in E3SM models.  https://acme-climate.atlassian.net/wiki/spaces/SE/pages/155124152/Output+file+names

**Comment by golaz** [comment]
@sterlingbaldwin : the short term archiving is now working. Here is an example on NERSC of directory structure:

`/global/cscratch1/sd/golaz/ACME_simulations/20170915.beta2.A_WCYCL1850S.ne30_oECv3_ICG.edison/archive`
