### ISSUE TITLE
No need to keep climo and time series files on native grids

### ISSUE THREAD

**Issue by golaz** [ACME-Climate/acme_processflow#23]
Once the climo and time series files have been regridded, there is no need to keep the native cubed-sphere grid files. They should be deleted. If someone ever needs them, they can be re-generated from the archived model history files.

**Comment by sterlingbaldwin** [comment]
Thanks for creating these issues @golaz!

**Comment by sterlingbaldwin** [comment]
Im going to add a config option for post_run_cleanup, which will remove all output files which use the native grid.

**Comment by sterlingbaldwin** [comment]
Fixed in the latest nightly, will close when I merge into master.
