### ISSUE TITLE
No timeseries files for year set 2

### ISSUE THREAD

**Issue by golaz** [ACME-Climate/acme_processflow#25]
I updated my most recent test (`/p/cscratch/acme/golaz1/20170915.beta2.A_WCYCL1850S.ne30_oECv3_ICG.edison/input/run.cfg`) to add processing of the second year set (11-20).

The screen tells me that the timeseries are complete, but I cannot find any trace of them. 

![win1](https://user-images.githubusercontent.com/15743046/30621927-22b05dd6-9d63-11e7-873f-75f237a5c3d6.png)

There is nothing from the second year set under:
`/p/cscratch/acme/golaz1/20170915.beta2.A_WCYCL1850S.ne30_oECv3_ICG.edison/output/monthly/10yr`

```
acme1> cd /p/cscratch/acme/golaz1/20170915.beta2.A_WCYCL1850S.ne30_oECv3_ICG.edison/output/monthly/10yr
acme1> ls
FLNS_000101_001012_fv129x256_aave.nc	PRECL_000101_001012_fv129x256_aave.nc
FLNS_000101_001012.nc			PRECL_000101_001012.nc
FLNT_000101_001012_fv129x256_aave.nc	PRECSC_000101_001012_fv129x256_aave.nc
FLNT_000101_001012.nc			PRECSC_000101_001012.nc
FLUT_000101_001012_fv129x256_aave.nc	PRECSL_000101_001012_fv129x256_aave.nc
FLUT_000101_001012.nc			PRECSL_000101_001012.nc
FSNS_000101_001012_fv129x256_aave.nc	QFLX_000101_001012_fv129x256_aave.nc
FSNS_000101_001012.nc			QFLX_000101_001012.nc
FSNT_000101_001012_fv129x256_aave.nc	SHFLX_000101_001012_fv129x256_aave.nc
FSNT_000101_001012.nc			SHFLX_000101_001012.nc
FSNTOA_000101_001012_fv129x256_aave.nc	TREFHT_000101_001012_fv129x256_aave.nc
FSNTOA_000101_001012.nc			TREFHT_000101_001012.nc
PRECC_000101_001012_fv129x256_aave.nc	TS_000101_001012_fv129x256_aave.nc
PRECC_000101_001012.nc			TS_000101_001012.nc
```

and in addition, there is no evidence of a timeseries script under

`/p/cscratch/acme/golaz1/20170915.beta2.A_WCYCL1850S.ne30_oECv3_ICG.edison/output/run_scripts`.

```
acme1> cd /p/cscratch/acme/golaz1/20170915.beta2.A_WCYCL1850S.ne30_oECv3_ICG.edison/output/run_scripts
acme1> ls -l
total 192
-rw------- 1 golaz1 climate 109308 Sep 19 15:58 amwg_11-20.csh
-rw------- 1 golaz1 climate    460 Sep 19 15:58 amwg_set_2_0011_0020_00740
-rw------- 1 golaz1 climate   2950 Sep 19 16:41 amwg_set_2_0011_0020_00740.err
-rw------- 1 golaz1 climate  48169 Sep 19 16:41 amwg_set_2_0011_0020_00740.out
-rw------- 1 golaz1 climate    780 Sep 19 15:39 ncclimo_set_2_0011_0020_b0072
-rw------- 1 golaz1 climate      0 Sep 19 15:39 ncclimo_set_2_0011_0020_b0072.err
-rw------- 1 golaz1 climate   3027 Sep 19 15:57 ncclimo_set_2_0011_0020_b0072.out
```

**Comment by golaz** [comment]
@sterlingbaldwin : I looked at the code to understand why this is not working. My hypothesis is that `postvalidate` in [Timeseries.py](https://github.com/ACME-Climate/acme_processflow/blob/master/jobs/Timeseries.py) is not working properly. 

When the job is executed for year set 2, it first calls `postvalidate` to check whether the work is already done. Because the files for year set 1 are there and because `postvalidate` doesn't do any check based on years, it sees year set 1 files and falsely assumes that the work is done.

**Comment by sterlingbaldwin** [comment]
When I saw this I realized the timeseries jobs dont create fresh directories for themselves. All the 10 year timeseries were being put in the same output directory. I just changed this so the directory structure will be something like:
```
monthly
├── 10yr
│   └── 0001-0010
│       ├── TS_000101_001012_fv129x256_aave.nc
│       └── TS_000101_001012.nc
└── 5yr
    ├── 0001-0005
    │   ├── TS_000101_000512_fv129x256_aave.nc
    │   └── TS_000101_000512.nc
    └── 0006-0010
        ├── TS_000601_001012_fv129x256_aave.nc
        └── TS_000601_001012.nc
```

**Comment by sterlingbaldwin** [comment]
This issue is fixed in verion 0.3.16 in the nightly label. Install with
```
conda install -c acme/label/nightly processflow
```

**Comment by golaz** [comment]
Ok for now, but not exactly the fix I was hoping for. I believe we had decided to keep all the time series with identical chunk length in the same sub-directory. However, we never had a full discussion on the complete directory structure. I'm starting to gather ideas for this and should have a proposal soon.

**Comment by sterlingbaldwin** [comment]
Ah I remember that now. I'll put them all back in the same directory and write a better post validator to check the years.

**Comment by golaz** [comment]
Worked in my most recent test!
