### ISSUE TITLE
Possible new directory structure for output files

### ISSUE THREAD

**Issue by golaz** [ACME-Climate/acme_processflow#29]
Not really an issue, but we may need to revisit the directory structure of output files generated by acme_processflow. The goal is to have a directory structure as simple as possible, while being general enough to handle new file types that we may want to generate in the future. This directory structure would reside under directory identifying the case name.

Here is an initial structure from a discussion with @PeterCaldwell.

Post-processed data files
--------------------------------

```
pp / <grid> / <frequency> / <type> / <chunk>
```
where

`pp` : post-processed data files
 `<grid>` : grid on which the data resides, either native or re-mapped
- ex: `ne30` (native) or `fv129x256` (remapped)

`<frequency>` : data frequency
- ex: `monthly`, `daily`, `8xdaily`, `hourly`, etc.

`<type>` : type of files
- `climo` for climatologies (12 monthly files, 4 seasonal, 1 annual)
- `ts` for time series files (one variable per file)

`<chunk>` : time period covered. 
- For climatologies, averaging period; for time series, length of data
- examples: `30yr`, `10yr`, `5yr`, `6mo`, ...

**Example**: 10 and 30 year climatologies from monthly model output, monthly time series files in 5 year chunks, daily time series in 1year chunks, everything remapped to fv129x256.

```
pp
 └── fv129x256
        ├── monthly
        │      ├── climo
        │      │    ├── 10yr
        │      │    └── 30yr
        │      └── ts
        │           └── 5yr
        └── daily
               └── ts
                    └── 1yr
```

Diagnostics figures
------------------------

```
diags / <grid> / <package> / <years>
```

`diags` : for diagnostic figures
`<grid>` : as above
`<package>` : diagnostic package name
- examples: `a-prime`, `acme-diags`, `mpas-analysis`, `amwg`, ...

`<years>` : time period covered
- examples: `0001-0010`, `1981-2010`, ...

**Comment by sterlingbaldwin** [comment]
So for the diagnostics you would want something like

    diags
     └── fv129x256
            ├── a-prime
            │      ├── 0010-0020
            │      └── 0001-0010
            └── amwg
                   ├── 0010-0020
                   └── 0001-0010

**Comment by sterlingbaldwin** [comment]
The updated directory structure in my new branch looks like this:
```
├── diags
│   └── fv129x256
│       ├── amwg
│       │   ├── 0001-0005
│       │   ├── ....
│       │   ├── 0106-0110
│       │   └── 0111-0115
│       ├── a-prime
│       │   ├── 0001-0010
│       │   ├── .....
│       │   └── 0101-0110
│       └── e3sm_diags
│           ├── 0001-0010
│           ├── ....
│           └── 0101-0110
├── pp
│   ├── fv129x256
│   │   ├── climo
│   │   │   ├── 10yr
│   │   │   └── 5yr
│   │   └── monthly
│   │       └── ts
│   │           └── 10yr
│   └── ne30
│        └── climo
│         ├── 10yr
│         └── 5yr
├── run_scripts
├── run_state.txt
├── tmp
└── workflow.log
```
Is that about what you were thinking @golaz?
