### ISSUE TITLE
can't find acme-viewer 

### ISSUE THREAD

**Issue by mccoy20** [ACME-Climate/acme_processflow#30]
I run this case:  /p/cscratch/acme/mccoy20/test_2017-09-14-Qi . ncclimo and AMWG were completed. I am trying to find the plots on the web. In ./output/workflow.log I can see 
'host_url': 'https://acme-viewer.llnl.gov/mccoy20/20170628.POP_MG2.A_WCYCL1850.ne30
_g16.edison/amwg/0041-0045',
but when I try to open it in a browser, the file is 'Not Found'.

I had run this case last Tuesday, restarted it today after updating, to see if the  acme-diags would get calculated, so far it says 'JobStatus.PENDING', same for coupled_diags.

**Comment by sterlingbaldwin** [comment]
It looks like your image host directory wasnt created. Im not sure why this would happen but not give you an error.

**Comment by sterlingbaldwin** [comment]
Fixed in the new nightly build.
