### ISSUE TITLE
update did not work

### ISSUE THREAD

**Issue by mccoy20** [ACME-Climate/acme_processflow#31]
I tired to update the processflow with command
> conda update –c acme processflow
It did not work.

I am not sure if we can use this command to update or we need to install it over every time with 'conda create ...'. Could you please add the updating to the documentation?

Here is the error I am getting
--------------------------
bash-4.1$ > conda update –c acme processflow
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.3.21
       conda is private : False
      conda-env version : 4.3.21
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.14.2
       root environment : /export/mccoy20/anaconda2  (writable)
    default environment : /export/mccoy20/anaconda2
       envs directories : /export/mccoy20/anaconda2/envs
                          /export/mccoy20/.conda/envs
          package cache : /export/mccoy20/anaconda2/pkgs
                          /export/mccoy20/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.21 requests/2.14.2 CPython/2.7.13 Linux/2.6.32-696.6.3.el6.x86_64 Red Hat Enterprise Linux Server/6.9 glibc/2.12    
                UID:GID : 53336:1026

`$ /export/mccoy20/anaconda2/bin/conda update –c acme processflow`

    Traceback (most recent call last):
      File "/export/mccoy20/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 632, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/export/mccoy20/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/export/mccoy20/anaconda2/lib/python2.7/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/export/mccoy20/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 152, in install
        common.arg2spec(name, json=context.json, update=True)
      File "/export/mccoy20/anaconda2/lib/python2.7/site-packages/conda/cli/common.py", line 510, in arg2spec
        return str(spec)
    UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 0: ordinal not in range(128)

**Comment by sterlingbaldwin** [comment]
try ```conda install -c acme/label/nightly processflow``` the new version should be 0.3.17-devel
