### ISSUE TITLE
Running the script again wiped out previous log and error files. The input and output data also disappeared.

### ISSUE THREAD

**Issue by mccoy20** [ACME-Climate/acme_processflow#33]
Since the acme_diags were not calculated, I tried to run updated processflow on the previous run (with input files already transferred and amwg and ncclimo already finished). The process claims: '[+] All processing complete'. Looking for the previous logs and errors, I noticed that the new run overwritten the old files. Looking further, both my input data (except case_scripts) and the output were wiped out as well.

I propose to always write the new state, log and error files, maybe append the date-time stamp to them. 

I am not sure how the input and output data were deleted, might be the user error, but obviously that should never be done.

directory: /p/cscratch/acme/mccoy20/test_2017-09-14-Chris

--------
(workflow) bash-4.1$ processflow.py -c ./run.cfg

acme1.llnl.gov requires manual activation, please open the following URL in a browser to activate the endpoint:
https://www.globus.org/app/endpoints/a871c6de-2acd-11e7-bc7c-22000b9a448b/activate 

Press ENTER after activating the endpoint

edisongrid.nersc.gov requires manual activation, please open the following URL in a browser to activate the endpoint:
https://www.globus.org/app/endpoints/b9d02196-6d04-11e5-ba46-22000b92c6ec/activate 

Press ENTER after activating the endpoint
Globus authentication complete
Checking file access on globus transfer nodes
Turning on the display........

[+] All processing complete

**Comment by sterlingbaldwin** [comment]
The config includes:
```
# The year to start the post processing, typically 1
simulation_start_year =  1980

# The last year to run post processing jobs on
simulation_end_year = 10
```
Thats your problem. I updated the docs yesterday (so you probably havent seen the changes). The new sample run config includes a better explanation of what those fields should be. The tool isnt seeing anything to run, since year 10 doesnt come after year 1980.

```
# The year to start the post processing, typically 1
# If the first year of the simulation is 0001, use 1, but if
#  it started later e.g. 1980, use 1980
simulation_start_year =  1

# The last year to run post processing jobs on
# The highest number year, so if your simulation starts in 1980
#   and you want to process 20 years, this should be 2000
simulation_end_year = 20
```

**Comment by mccoy20** [comment]
OK. I will change that and re-run. 

Please add the check and give a user an error if the simulation_end_year is lower then simulation_start_year. Also if you cannot find data with given year specification -- also give a warning on that.
