### ISSUE TITLE
Status screen not reporting properly

### ISSUE THREAD

**Issue by golaz** [ACME-Climate/acme_processflow#36]
The main processflow screen is not reporting properly the status of the post-processing. Here is an example from `/p/cscratch/acme/golaz1/20170824.FCTfix-GM.A_WCYCL1850S.ne30_oECv3.anvil/input`

![win2](https://user-images.githubusercontent.com/15743046/30819313-31efe572-a1d3-11e7-8eee-d1dda37b9bee.png)

The screen indicates that ncclimo for year set 31-60 has been running for over 13 hours, but there is nothing in the queue

```
acme1:~> squeue
             JOBID PARTITION     NAME     USER ST       TIME  NODES NODELIST(REASON)
```

**Comment by golaz** [comment]
Just experienced similar problem again. The screen is showing jobs are RUNNING, but squeue is returning nothing.

**Comment by sterlingbaldwin** [comment]
Thanks @golaz, I know where this problem is and will have it fixed today.

**Comment by golaz** [comment]
Thanks, @sterlingbaldwin. Let me know when you have a new version ready to be tested.

**Comment by sterlingbaldwin** [comment]
This should hopefully all be solved with the new Slurm interface.
