### ISSUE TITLE
acme-viewer should show all user's runs outputs - permissions 

### ISSUE THREAD

**Issue by mccoy20** [ACME-Climate/acme_processflow#39]
It would be good to have access (permissions) to see all the run's one has in their acme-viewer, ie
if I go to 
https://acme-viewer.llnl.gov/mccoy20/

I would like to see what is inside there, and be able to walk the directories there.

**Comment by mccoy20** [comment]
Explaining more on this, looking at 
https://acme-viewer.llnl.gov/golaz1/20170915.beta2.A_WCYCL1850S.ne30_oECv3_ICG.edison/amwg/0001-0010/index.html

I would like to be able to see what is in

https://acme-viewer.llnl.gov/golaz1/20170915.beta2.A_WCYCL1850S.ne30_oECv3_ICG.edison/amwg/ 

as well as in

https://acme-viewer.llnl.gov/golaz1/20170915.beta2.A_WCYCL1850S.ne30_oECv3_ICG.edison/

**Comment by sterlingbaldwin** [comment]
Complete.
