### ISSUE TITLE
Improved documentation

### ISSUE THREAD

**Issue by sterlingbaldwin** [ACME-Climate/acme_processflow#4]
Documentation needs to be upgraded significantly. Currently there's no explanation of how the jobs are related to each other, or any dependencies between them. I would like to use sphinx to generate some pages, then make a github.io page for the tool.

**Comment by golaz** [comment]
Would suggest to use sphinx and host directly on github. For example, see:

https://acme-climate.github.io/zstash/docs/html/contributing.html

**Comment by sterlingbaldwin** [comment]
This is what I was thinking. Sphinx makes great looking doc pages, I just havent used it much so I'll have to learn a bit.

**Comment by golaz** [comment]
@sterlingbaldwin : since I have done this before, I can take a first cut at converting to Sphinx. For hosting using Github pages, there are two options:

1. Create a separate branch called 'gh-pages' where the documentation lives.
2. Maintain the documentation under a 'docs' sub-directory on master.

I personally prefer (1) because (2) will clutter master with a lot of unnecessary commits (for example every time one regenerates the static html files with Sphinx).

**Comment by rljacob** [comment]
@jhkennedy straightened out the CIME use of Sphinx and github pages.  See https://github.com/ESMCI/cime/issues/1338#issuecomment-304361515

**Comment by jhkennedy** [comment]
@golaz and @sterlingbaldwin I'd suggest doing both 1 and 2. (thanks for the shout-out @rljacob)

To summarize that commit message/issue discussion:
 
Having the documentation within the code base in a `docs` directory means you can enforce parallel documentation and code updates (e.g., don't satisfy a PR without the docs also being updated). Also, this allows you to use the automatic code parsing tools like autodocs/automodule to generate documentation for your API/functions/classes/etc directly from their docstrings. So, functions are directly documented within the function (same for classes/modules/etc.). 


Then, you'd set up an *orphaned* `gh-pages` branch that *only* stores the generated HTML docs and you'd have the generated documentation ignored by git in the master/feature/development branches (typically, you'd have sphinx build into a `docs/_build` directory, which is ignored in your `.gitignore` file). 

As you integrate a PR, you'd have the integrator make a new version of the HTML docs and copy the generated HTML into the `gh-pages` branch to update the website (it's easiest to have the gh-pages branch as a separate checkout, so all you're doing is a `cp` into that directory and then pushing the changes). 

With this strategy, you don't get HTML clutter in your repos, but you do get the advantages of parallel documentation.

**Comment by jhkennedy** [comment]
Also, I'm happy to help you guys set it up -- I've worked with sphinx quite a bit now. :-)

**Comment by golaz** [comment]
@jhkennedy : thank you for your suggestion. I like your hybrid approach: keeping the doc source on `master` and the html build on `gh-pages`. I never thought about it. This is elegant and avoids many of the drawbacks from either pure approach. The only slight challenge is the moving of the generated html pages to the `gh-pages` branch. But maybe in the future, the build and update of `gh-pages` could even be automated to make the process seamless.

Also, I'm happy to take you on your offer to setup a first version for of the documentation with sphinx. I'm assuming @sterlingbaldwin will be happy for the help as well. Personally, I like the 'readthedocs' theme, unless you have a better suggestion. @rljacob: maybe someone should create a E3SM sphinx theme? We have PowerPoints templates, why not a sphinx theme?

**Comment by sterlingbaldwin** [comment]
The first draft of the docs can be found [here](https://acme-climate.github.io/acme_workflow/docs/html/index.html) using the gh-pages approach and Chris's readthedocs theme.

**Comment by mccoy20** [comment]
Please add 'bash' command to the installation instructions before the 'source...' command. Thanks!

**Comment by mccoy20** [comment]
Please add the instructions on how to get run.cfg

**Comment by sterlingbaldwin** [comment]
Thanks @mccoy20, I had the link in but there was a ' instead of a ` so it didnt render properly. I added a note that all commands are for the Bourne Again Shell. Although a link to the sample config can now be found in the quickstart guide, you can also [go directly to it](https://acme-climate.github.io/acme_workflow/docs/html/sample.html)
