### ISSUE TITLE
Retrying previous job - errors on coupled_diags or  acme_diags 

### ISSUE THREAD

**Issue by mccoy20** [ACME-Climate/acme_processflow#43]
directory:  /export/mccoy20/pRen/test_2017-09-14-Chris/

Tried to update process flow and acme_diags. May have messed up stuff.

Here is what I did
  >conda clean --all
  >conda install acme_diags -c acme -c conda-forge -c uvcdat
could not do that because it wanted to write to /usr/local , so abandoned that

 > conda create -n workflow -c acme -c conda-forge -c uvcdat  -c lukasz processflow
(not sure if I did the > conda create -n workflow -c acme -c conda-forge -c uvcdat  -c lukasz processflow 
or not ??)

then run the script, it started fine, found the data, started on acme_diags, then showed error of a moment, then cleanly close the opened display (before I wrote the error :) . )

Here is the workflow.error:
------
Exception in thread monitor_job for coupled_diags:
Traceback (most recent call last):
  File "/export/mccoy20/anaconda2/envs/workflow/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/export/mccoy20/anaconda2/envs/workflow/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "build/bdist.linux-x86_64/egg/lib/util.py", line 455, in monitor_job
    job_id = job.execute(batch='slurm')
  File "build/bdist.linux-x86_64/egg/jobs/CoupledDiagnostic.py", line 257, in execute
    setup_status = self.setup_input_directory()
  File "build/bdist.linux-x86_64/egg/jobs/CoupledDiagnostic.py", line 221, in setup_input_directory
    loggig.error(msg)
NameError: global name 'loggig' is not defined

Exception in thread monitor_job for coupled_diags:
Traceback (most recent call last):
  File "/export/mccoy20/anaconda2/envs/workflow/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/export/mccoy20/anaconda2/envs/workflow/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "build/bdist.linux-x86_64/egg/lib/util.py", line 455, in monitor_job
    job_id = job.execute(batch='slurm')
  File "build/bdist.linux-x86_64/egg/jobs/CoupledDiagnostic.py", line 257, in execute
    setup_status = self.setup_input_directory()
  File "build/bdist.linux-x86_64/egg/jobs/CoupledDiagnostic.py", line 221, in setup_input_directory
    loggig.error(msg)
NameError: global name 'loggig' is not defined
----

**Comment by mccoy20** [comment]
Here is the email I got
---
One or more job failed

Execution state as of 27, Sep 2017 09:45
Running under process 179891

Year_set 1: 1980 - 1984
status: SetStatus.FAILED
  >   ncclimo -- 0: JobStatus.COMPLETED
  >   amwg -- 0: JobStatus.COMPLETED
  >   acme_diags -- 541: JobStatus.FAILED

Year_set 2: 1985 - 1989
status: SetStatus.FAILED
  >   ncclimo -- 0: JobStatus.COMPLETED
  >   amwg -- 0: JobStatus.COMPLETED
  >   acme_diags -- 543: JobStatus.FAILED

Year_set 3: 1990 - 1994
status: SetStatus.FAILED
  >   ncclimo -- 0: JobStatus.COMPLETED
  >   amwg -- 0: JobStatus.COMPLETED
  >   acme_diags -- 545: JobStatus.FAILED

Year_set 4: 1995 - 1999
status: SetStatus.FAILED
  >   ncclimo -- 0: JobStatus.COMPLETED
  >   amwg -- 0: JobStatus.COMPLETED
  >   acme_diags -- 546: JobStatus.FAILED

Year_set 5: 1980 - 1989
status: SetStatus.FAILED
  >   ncclimo -- 0: JobStatus.COMPLETED
  >   timeseries -- 0: JobStatus.COMPLETED
  >   coupled_diags -- 0: JobStatus.VALID
  >   amwg -- 0: JobStatus.COMPLETED
  >   acme_diags -- 544: JobStatus.FAILED

Year_set 6: 1990 - 1999
status: SetStatus.FAILED
  >   ncclimo -- 0: JobStatus.COMPLETED
  >   timeseries -- 0: JobStatus.COMPLETED
  >   coupled_diags -- 0: JobStatus.VALID
  >   amwg -- 547: JobStatus.RUNNING
  >   acme_diags -- 542: JobStatus.FAILED


Initializing year sets
Added 6 year sets to the queue
Initializing file list
Attempting connection to source endpoint
Endpoint is already activated and does not expire before the requested if_expires_in.
Connected
Running check for remote files
Found 1 new remote files, moving data from STREAMS: to STREAMS:
Timeseries already computed, skipping
Timeseries already computed, skipping
Ncclimo job already computed, skipping
Ncclimo job already computed, skipping
Ncclimo job already computed, skipping
Ncclimo job already computed, skipping
Ncclimo job already computed, skipping
Ncclimo job already computed, skipping
acme_diags id: 541 changed state to PENDING
Submitted acme_diags for year_set 1
acme_diags id: 542 changed state to PENDING
Submitted acme_diags for year_set 6
acme_diags id: 543 changed state to PENDING
Submitted acme_diags for year_set 2
acme_diags id: 544 changed state to PENDING
Submitted acme_diags for year_set 5
acme_diags id: 545 changed state to PENDING
Submitted acme_diags for year_set 3
acme_diags id: 546 changed state to PENDING
Submitted acme_diags for year_set 4
amwg id: 547 changed state to JobStatus.SUBMITTED
Submitted amwg for year_set 6
AMWG job already computed, skipping
AMWG job already computed, skipping
AMWG job already computed, skipping
AMWG job already computed, skipping
Setting up local hosting for amwg
AMWG job already computed, skipping
Setting up local hosting for amwg
Setting up local hosting for amwg
Setting up local hosting for amwg
Setting up local hosting for amwg
Job 541 has failed
Job 542 has failed
Job 543 has failed
Job 544 has failed
Job 545 has failed
Job 546 has failed
09:45 Transfer in progress  (1/1) [********************] 100.00%
amwg hosted at https://acme-viewer.llnl.gov/mccoy20/20170731.F20TR_ck10.ne30_ne30.edison/amwg/1995-1999/index.html
amwg hosted at https://acme-viewer.llnl.gov/mccoy20/20170731.F20TR_ck10.ne30_ne30.edison/amwg/1990-1994/index.html
amwg hosted at https://acme-viewer.llnl.gov/mccoy20/20170731.F20TR_ck10.ne30_ne30.edison/amwg/1980-1989/index.html
amwg hosted at https://acme-viewer.llnl.gov/mccoy20/20170731.F20TR_ck10.ne30_ne30.edison/amwg/1980-1984/index.html
amwg hosted at https://acme-viewer.llnl.gov/mccoy20/20170731.F20TR_ck10.ne30_ne30.edison/amwg/1985-1989/index.html

**Comment by sterlingbaldwin** [comment]
For the time being dont run with coupled_diags, theres at least one bug that Im not going to fix since I need to transition to the new a-prime version that just got released.
