### ISSUE TITLE
short name for acme_diags and AMWG

### ISSUE THREAD

**Issue by sterlingbaldwin** [ACME-Climate/acme_processflow#78]
The experiment short name should be used for acme_diags and AMWG.

**Comment by golaz** [comment]
- For ACME Diags, there is an option called 'short_test_name' in the configuration file.
- For AMWG, I do the following:

`setenv TITLE "${NAME}_(${YEAR1}-${YEAR2})"`
where NAME is the short name, and YEAR1, YEAR2 the begin and end year.

In the AMWG main script (diag140804_YEAR1-YEAR2_vs_OBS.csh), I have

`set test_name = $TITLE`

**Comment by golaz** [comment]
This appears to be working fine now.
