### ISSUE TITLE
File transfer not working

### ISSUE THREAD

**Issue by golaz** [ACME-Climate/acme_processflow#8]
I started a new post-processing job this morning. The process starts, but nothing happens and no files are being transferred from LCRC to acme1. I verified that both globus nodes are up and running. I looked for, but could not find any log files with any information about what might be wrong.

Below is a screen shot of the window and a copy of the configuration file.

![screenshot](https://user-images.githubusercontent.com/15743046/29785086-26ec7a0e-8bdb-11e7-9bbd-2ce688087f4b.png)

[run.cfg.txt](https://github.com/ACME-Climate/acme_workflow/files/1257659/run.cfg.txt)

**Comment by sterlingbaldwin** [comment]
Im looking into this right now. Since I only use ssh keys to connect to blues Im trying to figure out what credentials to use for the globus authentication.

**Comment by rljacob** [comment]
Use your username and password that you use for your blues account web page.

**Comment by mccoy20** [comment]
I may be seeing the same problem, or at least the files are not transferred correctly in one of the job's I tried last Thursday and retried today with the code updated to the latest version. I see Globus notifications with 'SUCCEEDED' in the subject line. It claims the transfer was successful but when you click on the link provided, it says: "Bytes Transferred 0 B"

The job (killed now) is on acme1 in /export/mccoy20/pRen/test_2017-09-14-Chris

Here is the text from Globus link:

Task ID0b2a5e3c-9e5d-11e7-acf9-22000a92523b
OwnerRenata McCoy (mccoy20@globusid.org)
SourceNERSC Edison  [i]  
owner: nersc@globusid.org
Destinationacme1  [i]  
owner: sbaldwin@globusid.org
ConditionSUCCEEDED
Requested2017-09-20 04:40 pm
Completed2017-09-20 04:40 pm
Transfer Settings
transfer is not encrypted
transfer new or changed files where the checksum is different (sync level 3)
Files1
Directories0
Bytes Transferred0 B
Effective Speed0 B/s
Pending0
Succeeded1
Cancelled0
Expired0
Failed0
Retrying0
Skipped1

**Comment by sterlingbaldwin** [comment]
After looking at your config file and your data directory, it looks like you have the start year marked as 1, but your simulations lowest output year is
```
20170731.F20TR_ck10.ne30_ne30.edison.cam.h0.1980-01.nc
```

**Comment by mccoy20** [comment]
I was getting a lot of Globus notifications on files being transferred successfully, but with 0 bytes being transferred. Are you saying this is the same file trying to transfer over and over? Is there a way to have more meaningful messaging from Globus, ie. including a file name would be a real help.

Also it was not obvious to me that the years in the config file are related to the actual year of simulation and the year that is in a file name. Could add this to the documentation ?

**Comment by sterlingbaldwin** [comment]
Will update the docs!

**Comment by golaz** [comment]
I tried again today to process a job that ran on LCRC blues/anvil. Unfortunately, the file transfer is not working:

```
acme1> source activate workflow
acme1> cd /p/cscratch/acme/golaz1/20170824.FCTfix-GM.A_WCYCL1850S.ne30_oECv3.anvil/input
acme1> processflow.py -f -c run.cfg
Globus authentication complete
Checking file access on globus transfer nodes
ERROR! Unable to access source globus node
The node may be down, or you may not have access to the requested directory
```

To verify that this is not a Globus issue, I manually started a transfer for a few *.cam.h0*.nc files from LCRC to acme1 using the Globus web interface. The transfer works.

**Comment by sterlingbaldwin** [comment]
This is strange. That error only happens when it tries to query the source globus node and is given an error code. I'll change the error to print out the globus error as well so we can see better whats happening.
