### ISSUE TITLE
Missing a-prime missing plots and incorrect climo time period

### ISSUE THREAD

**Issue by golaz** [ACME-Climate/acme_processflow#93]
Running version processflow-1.0.0-rc5. Lots of missing a-prime figures and possible time series length problem.

For example, see:
https://acme-viewer.llnl.gov/golaz1/20180129.DECKv1a_piControl.ne30_oEC.edison/a-prime/0001-0100/

Example of missing plots:

- Global SST time series
- Global OHC time series
- NH, SH ice area and volume time series
- All ocean climatology plots
- Ocean Nino3.4 Index

Also, I requested A-Prime for the years 1 to 100, but the page says

"Climatological years: 1-10"

**Comment by sterlingbaldwin** [comment]
The page says 1-10, but all the aprime files say it ran 1-100. This is a strange issue, in the aprime run script I can see that the variables are being set correctly
```bash
export test_begin_yr_climo=1
export test_end_yr_climo=100
```

and in the aprime file that generates the html it only looks at those two variables when creating the html.

```html
${casename}<br>(Climatological years: $begin_yr_climo-$end_yr_climo) vs. $ref_case_text
```

My guess right now is that something internal to aprime must be changing the value of end_yr_climo.

**Comment by sterlingbaldwin** [comment]
Found the issue causing the incorrect years to appear. The diags were done on the correct years, the web page was just displaying the wrong information. Still tracking down the issue for the missing plots.

**Comment by sterlingbaldwin** [comment]
Found and fixed.
