### ISSUE TITLE
Creating conda env for processflow from env.yml failed - looking for processflow-1.0.0-rc5.tar.bz2

### ISSUE THREAD

**Issue by muryanto1** [ACME-Climate/acme_processflow#97]
$ wget https://raw.githubusercontent.com/ACME-Climate/acme_processflow/master/env.yml
$ conda create --name processflow --file env.yml
....
...
xorg-libxdmcp 1.1.2: ########################################################################## | 100%
xz 5.2.3: ##################################################################################### | 100%
yaml 0.1.6: ################################################################################### | 100%
zict 0.1.3: ################################################################################### | 100%
zlib 1.2.11: ################################################################################## | 100%
 
CondaHTTPError: HTTP 404 NOT FOUND for url <https://conda.anaconda.org/acme/linux-64/processflow-1.0.0-rc5.tar.bz2>
Elapsed: 00:00.401127
CF-RAY: 3f0486e259186e02-SJC
 
An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
 
I noticed in the url, there is a new file processflow-1.0.0-rc6.tar.bz2

**Comment by sterlingbaldwin** [comment]
Fixed
